export enum Permission {
  // Módulo: Usuarios (Trade Marketing)
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_GESTIONAR = 'USUARIOS_GESTIONAR',
  USUARIOS_PASSWORDS = 'USUARIOS_PASSWORDS',
  USUARIOS_ASIGNAR_RUTA = 'USUARIOS_ASIGNAR_RUTA',

  // Módulo: Reportes y KPI (Trade Marketing)
  REPORTES_VER_PROPIO = 'REPORTES_VER_PROPIO',
  REPORTES_VER_EQUIPO = 'REPORTES_VER_EQUIPO',
  REPORTES_VER_GLOBAL = 'REPORTES_VER_GLOBAL',
  REPORTES_EXPORTAR = 'REPORTES_EXPORTAR',
  REPORTES_GESTIONAR = 'REPORTES_GESTIONAR',

  // Módulo: Operación en Campo (Trade Marketing)
  VISITAS_REGISTRAR = 'VISITAS_REGISTRAR',
  VISITAS_VER = 'VISITAS_VER',
  VISITAS_AUDITAR = 'VISITAS_AUDITAR',

  // Módulo: Administración (Trade Marketing)
  CATALOGO_GESTIONAR = 'CATALOGO_GESTIONAR',
  PLANOGRAMAS_GESTIONAR = 'PLANOGRAMAS_GESTIONAR',
  ROLES_CONFIGURAR = 'ROLES_CONFIGURAR',
  SCORING_CONFIG_VER = 'SCORING_CONFIG_VER',
  SCORING_CONFIG_GESTIONAR = 'SCORING_CONFIG_GESTIONAR',

  // Módulo: Logística - Embarques
  LOG_EMBARQUES_VER = 'LOG_EMBARQUES_VER',
  LOG_EMBARQUES_CREAR = 'LOG_EMBARQUES_CREAR',
  LOG_EMBARQUES_EDITAR = 'LOG_EMBARQUES_EDITAR',
  LOG_EMBARQUES_ELIMINAR = 'LOG_EMBARQUES_ELIMINAR',

  // Módulo: Logística - Guías
  LOG_GUIAS_VER = 'LOG_GUIAS_VER',
  LOG_GUIAS_CREAR = 'LOG_GUIAS_CREAR',
  LOG_GUIAS_EDITAR = 'LOG_GUIAS_EDITAR',
  LOG_GUIAS_ELIMINAR = 'LOG_GUIAS_ELIMINAR',

  // Módulo: Logística - Unidades
  LOG_UNIDADES_VER = 'LOG_UNIDADES_VER',
  LOG_UNIDADES_GESTIONAR = 'LOG_UNIDADES_GESTIONAR',

  // Módulo: Logística - Colaboradores
  LOG_COLABORADORES_VER = 'LOG_COLABORADORES_VER',
  LOG_COLABORADORES_GESTIONAR = 'LOG_COLABORADORES_GESTIONAR',

  // Módulo: Logística - Catálogos
  LOG_CATALOGOS_VER = 'LOG_CATALOGOS_VER',
  LOG_CATALOGOS_GESTIONAR = 'LOG_CATALOGOS_GESTIONAR',

  // Módulo: Logística - Liquidaciones
  LOG_LIQUIDACIONES_VER = 'LOG_LIQUIDACIONES_VER',
  LOG_LIQUIDACIONES_GESTIONAR = 'LOG_LIQUIDACIONES_GESTIONAR',

  // Módulo: Logística - Reportes
  LOG_REPORTES_VER = 'LOG_REPORTES_VER',
  LOG_REPORTES_EXPORTAR = 'LOG_REPORTES_EXPORTAR',
}
