import { MongoAbility, createMongoAbility } from '@casl/ability';

export type Action = 'manage' | 'read' | 'create' | 'update' | 'delete';

export type AppSubject =
  | 'all'
  | 'users'
  | 'users_passwords'
  | 'users_assign_route'
  | 'catalogs'
  | 'stores'
  | 'stores_create'
  | 'planograms'
  | 'roles_config'
  | 'scoring_config'
  | 'visits'
  | 'visits_audit'
  | 'reports_own'
  | 'reports_team'
  | 'reports_global'
  | 'reports_export'
  | 'reports_manage'
  | 'kpi_goals'
  | 'team_management'
  | 'seguimiento'
  | 'routes_analytics'
  | 'commercial_map'
  | 'commercial_customers'
  | 'commercial_warehouses'
  | 'commercial_pricing'
  | 'commercial_inventory'
  | 'commercial_orders'
  | 'commercial_payments'
  | 'commercial_promotions'
  | 'commercial_televenta'
  | 'logistics_fleet'
  | 'logistics_shipments'
  | 'logistics_guides'
  | 'logistics_expenses'
  | 'logistics_payroll'
  | 'logistics_config'
  | 'capture_ticket'
  | 'route_ticket';

export type AppAbility = MongoAbility<[Action, AppSubject]>;
