tunnel: megadulcesservice
credentials-file: C:\Users\Sistemas\.cloudflared\megadulcesservice.json

ingress:
  # Trade Marketing API
  - hostname: api.megadulcesservice.trycloudflare.com
    service: http://localhost:3001
  # Trade Marketing View
  - hostname: megadulcesservice.trycloudflare.com
    service: http://localhost:82
  # Catch-all
  - service: http://status:404
