tunnel: <TUNNEL_ID>
credentials-file: /path/to/credentials/<TUNNEL_ID>.json

ingress:
  # Trade Marketing API
  - hostname: api.megadulces.com.mx
    service: http://localhost:3001
  # Trade Marketing View
  - hostname: megadulces.com.mx
    service: http://localhost:81
  # Catch-all
  - service: http://status:404
