export enum Permission {
  // Módulo: Usuarios
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_GESTIONAR = 'USUARIOS_GESTIONAR',
  USUARIOS_PASSWORDS = 'USUARIOS_PASSWORDS',
  USUARIOS_ASIGNAR_RUTA = 'USUARIOS_ASIGNAR_RUTA',

  // Módulo: Reportes y KPI
  REPORTES_VER_PROPIO = 'REPORTES_VER_PROPIO',
  REPORTES_VER_EQUIPO = 'REPORTES_VER_EQUIPO',
  REPORTES_VER_GLOBAL = 'REPORTES_VER_GLOBAL',
  REPORTES_EXPORTAR = 'REPORTES_EXPORTAR',

  // Módulo: Operación en Campo (Auditoría)
  VISITAS_REGISTRAR = 'VISITAS_REGISTRAR',
  VISITAS_VER = 'VISITAS_VER',
  VISITAS_AUDITAR = 'VISITAS_AUDITAR',

  // Módulo: Administración (Catálogos y Sistema)
  CATALOGO_GESTIONAR = 'CATALOGO_GESTIONAR',
  PLANOGRAMAS_GESTIONAR = 'PLANOGRAMAS_GESTIONAR',
  ROLES_CONFIGURAR = 'ROLES_CONFIGURAR',
  SCORING_CONFIG_VER = 'SCORING_CONFIG_VER',
  SCORING_CONFIG_GESTIONAR = 'SCORING_CONFIG_GESTIONAR',
}
