export enum Permission {
  // Usuarios
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_GESTIONAR = 'USUARIOS_GESTIONAR',
  USUARIOS_PASSWORDS = 'USUARIOS_PASSWORDS',
  USUARIOS_ASIGNAR_RUTA = 'USUARIOS_ASIGNAR_RUTA',

  // Reportes
  REPORTES_VER_PROPIO = 'REPORTES_VER_PROPIO',
  REPORTES_VER_EQUIPO = 'REPORTES_VER_EQUIPO',
  REPORTES_VER_GLOBAL = 'REPORTES_VER_GLOBAL',
  REPORTES_EXPORTAR = 'REPORTES_EXPORTAR',
  REPORTES_GESTIONAR = 'REPORTES_GESTIONAR',

  // Visitas
  VISITAS_REGISTRAR = 'VISITAS_REGISTRAR',
  VISITAS_VER = 'VISITAS_VER',
  VISITAS_AUDITAR = 'VISITAS_AUDITAR',

  // Catálogos
  CATALOGO_GESTIONAR = 'CATALOGO_GESTIONAR',
  PLANOGRAMAS_GESTIONAR = 'PLANOGRAMAS_GESTIONAR',
  TIENDAS_VER = 'TIENDAS_VER',
  TIENDAS_CREAR = 'TIENDAS_CREAR',

  // Configuración de Sistema
  ROLES_CONFIGURAR = 'ROLES_CONFIGURAR',
  SCORING_CONFIG_VER = 'SCORING_CONFIG_VER',
  SCORING_CONFIG_GESTIONAR = 'SCORING_CONFIG_GESTIONAR',

  // Seguimiento
  VER_SEGUIMIENTO = 'VER_SEGUIMIENTO',
}
