export enum Permission {
  // Usuarios
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_GESTIONAR = 'USUARIOS_GESTIONAR',
  USUARIOS_PASSWORDS = 'USUARIOS_PASSWORDS',
  USUARIOS_ASIGNAR_RUTA = 'USUARIOS_ASIGNAR_RUTA',

  // Reportes
  REPORTES_VER_PROPIO = 'REPORTES_VER_PROPIO',
  REPORTES_VER_EQUIPO = 'REPORTES_VER_EQUIPO',
  REPORTES_VER_GLOBAL = 'REPORTES_VER_GLOBAL',
  REPORTES_EXPORTAR = 'REPORTES_EXPORTAR',
  REPORTES_GESTIONAR = 'REPORTES_GESTIONAR',

  // Visitas
  VISITAS_REGISTRAR = 'VISITAS_REGISTRAR',
  VISITAS_VER = 'VISITAS_VER',
  VISITAS_AUDITAR = 'VISITAS_AUDITAR',

  // Catálogos
  CATALOGO_GESTIONAR = 'CATALOGO_GESTIONAR',
  PLANOGRAMAS_GESTIONAR = 'PLANOGRAMAS_GESTIONAR',
  TIENDAS_VER = 'TIENDAS_VER',
  TIENDAS_CREAR = 'TIENDAS_CREAR',

  // Configuración de Sistema
  ROLES_CONFIGURAR = 'ROLES_CONFIGURAR',
  SCORING_CONFIG_VER = 'SCORING_CONFIG_VER',
  SCORING_CONFIG_GESTIONAR = 'SCORING_CONFIG_GESTIONAR',

  // Seguimiento
  VER_SEGUIMIENTO = 'VER_SEGUIMIENTO',

  // Rutas (análisis: tiendas por ruta, tiempos de visita, trazabilidad)
  RUTAS_VER = 'RUTAS_VER',

  // Mapa Comercial (exhibidores Mega Dulces vs competencia + historial por tienda)
  COMMERCIAL_MAP_VER = 'COMMERCIAL_MAP_VER',

  // Supervisor AI de ejecución (Horus) — parte diario, auditoría visual, fraude
  SUPERVISOR_AI_VER = 'SUPERVISOR_AI_VER',
  SUPERVISOR_AI_APROBAR = 'SUPERVISOR_AI_APROBAR',

  // Comercial (Fase B+C)
  COMMERCIAL_CUSTOMERS_VER = 'COMMERCIAL_CUSTOMERS_VER',
  COMMERCIAL_CUSTOMERS_GESTIONAR = 'COMMERCIAL_CUSTOMERS_GESTIONAR',
  COMMERCIAL_WAREHOUSES_VER = 'COMMERCIAL_WAREHOUSES_VER',
  COMMERCIAL_WAREHOUSES_GESTIONAR = 'COMMERCIAL_WAREHOUSES_GESTIONAR',
  COMMERCIAL_PRICING_VER = 'COMMERCIAL_PRICING_VER',
  COMMERCIAL_PRICING_GESTIONAR = 'COMMERCIAL_PRICING_GESTIONAR',
  COMMERCIAL_INVENTORY_VER = 'COMMERCIAL_INVENTORY_VER',
  COMMERCIAL_INVENTORY_AJUSTAR = 'COMMERCIAL_INVENTORY_AJUSTAR',
  COMMERCIAL_INVENTORY_CONTAR = 'COMMERCIAL_INVENTORY_CONTAR',
  COMMERCIAL_INVENTORY_SUPERVISAR = 'COMMERCIAL_INVENTORY_SUPERVISAR',
  COMMERCIAL_INVENTORY_RECONCILIAR = 'COMMERCIAL_INVENTORY_RECONCILIAR',
  COMMERCIAL_INVENTORY_ASIGNAR = 'COMMERCIAL_INVENTORY_ASIGNAR',
  COMMERCIAL_ORDERS_VER = 'COMMERCIAL_ORDERS_VER',
  COMMERCIAL_ORDERS_CREAR = 'COMMERCIAL_ORDERS_CREAR',
  COMMERCIAL_ORDERS_CONFIRMAR = 'COMMERCIAL_ORDERS_CONFIRMAR',
  COMMERCIAL_ORDERS_CANCELAR = 'COMMERCIAL_ORDERS_CANCELAR',
  COMMERCIAL_ORDERS_FULFILL = 'COMMERCIAL_ORDERS_FULFILL',
  COMMERCIAL_PAYMENTS_REGISTRAR = 'COMMERCIAL_PAYMENTS_REGISTRAR',

  // Promociones (Fase G.2)
  COMMERCIAL_PROMOTIONS_VER = 'COMMERCIAL_PROMOTIONS_VER',
  COMMERCIAL_PROMOTIONS_GESTIONAR = 'COMMERCIAL_PROMOTIONS_GESTIONAR',

  // Televenta / Remote Manager (Fase E)
  COMMERCIAL_TELEVENTA_VER = 'COMMERCIAL_TELEVENTA_VER',
  COMMERCIAL_TELEVENTA_OPERATE = 'COMMERCIAL_TELEVENTA_OPERATE',

  // Fase V — Vendedor con OCR de ticket
  CAPTURE_TICKET_USE = 'CAPTURE_TICKET_USE',

  // Acceso a la app de vendedor standalone (gate administrable desde /admin/roles)
  VENDOR_APP_ACCESS = 'VENDOR_APP_ACCESS',

  // Comercial — Cierre de ruta (tickets venta/carga/combustible)
  ROUTE_TICKET_CAPTURE = 'ROUTE_TICKET_CAPTURE',
  ROUTE_CONTROL_VER = 'ROUTE_CONTROL_VER',

  // Logística (Fase J)
  LOGISTICS_FLEET_VER = 'LOGISTICS_FLEET_VER',
  LOGISTICS_FLEET_GESTIONAR = 'LOGISTICS_FLEET_GESTIONAR',
  LOGISTICS_SHIPMENTS_VER = 'LOGISTICS_SHIPMENTS_VER',
  LOGISTICS_SHIPMENTS_GESTIONAR = 'LOGISTICS_SHIPMENTS_GESTIONAR',
  LOGISTICS_GUIDES_VER = 'LOGISTICS_GUIDES_VER',
  LOGISTICS_GUIDES_GESTIONAR = 'LOGISTICS_GUIDES_GESTIONAR',
  LOGISTICS_EXPENSES_VER = 'LOGISTICS_EXPENSES_VER',
  LOGISTICS_EXPENSES_GESTIONAR = 'LOGISTICS_EXPENSES_GESTIONAR',
  LOGISTICS_PAYROLL_VER = 'LOGISTICS_PAYROLL_VER',
  LOGISTICS_PAYROLL_GESTIONAR = 'LOGISTICS_PAYROLL_GESTIONAR',
  LOGISTICS_CONFIG_GESTIONAR = 'LOGISTICS_CONFIG_GESTIONAR',
  LOGISTICS_CARTAPORTE_VER = 'LOGISTICS_CARTAPORTE_VER',
  LOGISTICS_CARTAPORTE_GESTIONAR = 'LOGISTICS_CARTAPORTE_GESTIONAR',
}
