export enum Permission {
  // Módulo: Usuarios
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_GESTIONAR = 'USUARIOS_GESTIONAR',
  USUARIOS_PASSWORDS = 'USUARIOS_PASSWORDS',
  USUARIOS_ASIGNAR_RUTA = 'USUARIOS_ASIGNAR_RUTA',

  // Módulo: Reportes y KPI
  REPORTES_VER_PROPIO = 'REPORTES_VER_PROPIO',
  REPORTES_VER_EQUIPO = 'REPORTES_VER_EQUIPO',
  REPORTES_VER_GLOBAL = 'REPORTES_VER_GLOBAL',
  REPORTES_EXPORTAR = 'REPORTES_EXPORTAR',
  REPORTES_GESTIONAR = 'REPORTES_GESTIONAR',

  // Módulo: Operación en Campo (Auditoría)
  VISITAS_REGISTRAR = 'VISITAS_REGISTRAR',
  VISITAS_VER = 'VISITAS_VER',
  VISITAS_AUDITAR = 'VISITAS_AUDITAR',

  // Módulo: Administración (Catálogos y Sistema)
  CATALOGO_GESTIONAR = 'CATALOGO_GESTIONAR',
  PLANOGRAMAS_GESTIONAR = 'PLANOGRAMAS_GESTIONAR',
  TIENDAS_VER = 'TIENDAS_VER',
  TIENDAS_CREAR = 'TIENDAS_CREAR',
  ROLES_CONFIGURAR = 'ROLES_CONFIGURAR',
  SCORING_CONFIG_VER = 'SCORING_CONFIG_VER',
  SCORING_CONFIG_GESTIONAR = 'SCORING_CONFIG_GESTIONAR',

  // Módulo: Seguimiento
  VER_SEGUIMIENTO = 'VER_SEGUIMIENTO',

  // Módulo: Rutas (análisis: tiendas por ruta, tiempos de visita, trazabilidad)
  RUTAS_VER = 'RUTAS_VER',

  // Módulo: Mapa Comercial (exhibidores Mega Dulces vs competencia en mapa + historial por tienda)
  COMMERCIAL_MAP_VER = 'COMMERCIAL_MAP_VER',

  // Módulo: Comercial — Clientes B2B (Fase B)
  COMMERCIAL_CUSTOMERS_VER = 'COMMERCIAL_CUSTOMERS_VER',
  COMMERCIAL_CUSTOMERS_GESTIONAR = 'COMMERCIAL_CUSTOMERS_GESTIONAR',

  // Módulo: Comercial — Almacenes y Pricing
  COMMERCIAL_WAREHOUSES_VER = 'COMMERCIAL_WAREHOUSES_VER',
  COMMERCIAL_WAREHOUSES_GESTIONAR = 'COMMERCIAL_WAREHOUSES_GESTIONAR',
  COMMERCIAL_PRICING_VER = 'COMMERCIAL_PRICING_VER',
  COMMERCIAL_PRICING_GESTIONAR = 'COMMERCIAL_PRICING_GESTIONAR',

  // Módulo: Comercial — Inventario
  COMMERCIAL_INVENTORY_VER = 'COMMERCIAL_INVENTORY_VER',
  COMMERCIAL_INVENTORY_AJUSTAR = 'COMMERCIAL_INVENTORY_AJUSTAR',

  // Módulo: Comercial — Pedidos y Cobros (Sprint B.2, declarados acá para tener el set completo)
  COMMERCIAL_ORDERS_VER = 'COMMERCIAL_ORDERS_VER',
  COMMERCIAL_ORDERS_CREAR = 'COMMERCIAL_ORDERS_CREAR',
  COMMERCIAL_ORDERS_CONFIRMAR = 'COMMERCIAL_ORDERS_CONFIRMAR',
  COMMERCIAL_ORDERS_CANCELAR = 'COMMERCIAL_ORDERS_CANCELAR',
  COMMERCIAL_ORDERS_FULFILL = 'COMMERCIAL_ORDERS_FULFILL',
  COMMERCIAL_PAYMENTS_REGISTRAR = 'COMMERCIAL_PAYMENTS_REGISTRAR',

  // Módulo: Comercial — Promociones (Fase G.2)
  COMMERCIAL_PROMOTIONS_VER = 'COMMERCIAL_PROMOTIONS_VER',
  COMMERCIAL_PROMOTIONS_GESTIONAR = 'COMMERCIAL_PROMOTIONS_GESTIONAR',

  // Módulo: Comercial — Televenta / Remote Manager (Fase E)
  COMMERCIAL_TELEVENTA_VER = 'COMMERCIAL_TELEVENTA_VER',
  COMMERCIAL_TELEVENTA_OPERATE = 'COMMERCIAL_TELEVENTA_OPERATE',

  // Fase V — Vendedor de campo con OCR de ticket
  CAPTURE_TICKET_USE = 'CAPTURE_TICKET_USE',

  // Módulo: Comercial — Cierre de ruta (tickets venta/carga/combustible)
  ROUTE_TICKET_CAPTURE = 'ROUTE_TICKET_CAPTURE', // vendedor: subir/ver sus tickets
  ROUTE_CONTROL_VER = 'ROUTE_CONTROL_VER', // admin: ver todos + reportes de ruta

  // Módulo: Logística — Flotilla y choferes (Fase J)
  LOGISTICS_FLEET_VER = 'LOGISTICS_FLEET_VER',
  LOGISTICS_FLEET_GESTIONAR = 'LOGISTICS_FLEET_GESTIONAR',

  // Módulo: Logística — Embarques (state machine)
  LOGISTICS_SHIPMENTS_VER = 'LOGISTICS_SHIPMENTS_VER',
  LOGISTICS_SHIPMENTS_GESTIONAR = 'LOGISTICS_SHIPMENTS_GESTIONAR',

  // Módulo: Logística — Guías + destinatarios
  LOGISTICS_GUIDES_VER = 'LOGISTICS_GUIDES_VER',
  LOGISTICS_GUIDES_GESTIONAR = 'LOGISTICS_GUIDES_GESTIONAR',

  // Módulo: Logística — Costos del viaje
  LOGISTICS_EXPENSES_VER = 'LOGISTICS_EXPENSES_VER',
  LOGISTICS_EXPENSES_GESTIONAR = 'LOGISTICS_EXPENSES_GESTIONAR',

  // Módulo: Logística — Liquidaciones y períodos
  LOGISTICS_PAYROLL_VER = 'LOGISTICS_PAYROLL_VER',
  LOGISTICS_PAYROLL_GESTIONAR = 'LOGISTICS_PAYROLL_GESTIONAR',

  // Módulo: Logística — Configuración financiera (factores, costo km)
  LOGISTICS_CONFIG_GESTIONAR = 'LOGISTICS_CONFIG_GESTIONAR',
}
